language: python
sudo: false
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install tox-travis
script:
- tox
deploy:
  provider: pypi
  user: dangle
  password:
    secure: PgVFsaNvHX2c8rm0JHvypFYC4cnIvozr8OdGSl/AUdOAswffYBGgUatxJ4O7JbKvC1Ig0nIj5C6XAgxPuw9qsJ+Xkfdo1htVF6AEVPD/1n4rHstO3bToZV0STOJYZbKpPuugr2Y6lXlMDUKNjfsPq0A6KLaksXSvkW3/LZ81zncW5b+jMrfndZRuA64xN59qEAk2vFsvTYaVQOXJ9JgSTJ3OdTmcbTm1x+jzhDXqEL64RHDNLt+Ca5JSNagfSYyNx85J/3l36t76E4GH2pD3NEIfaIO2EQmqk1CPknhdUaGZUpVBP+6vitmrWShzVBSNgBbdTwonyYpqdrqp/YcIDSzD+QuLbrOLOmXRCDVTmmBwXp5+0wcDxolCXKFltrn5PdINBas70gAkiv3IKGMjggbD5vgZhp3hPMHSwalPtcAIFLIFFI2mXXVSyxJqtBz2pmSNhwdaFyeUU9hSC4/02Y9nqVePoxfVMAeybPnMckLFLW4EDgp1tNoepugMt8RSEQTMRcrTvkjZ9FtPNCHzAC909pLHqBHvK4CVx9+uxQQIR8peeg/bSODcvMYZ2frFkLiv/xBa5xL3Z57juKdEzRxycbrUzVBQML/KOUwL3WPSb8xk3NRD+69WLyzudFWuiShgtBcSZ2GWC/c1bUQKqH0bY8rUhOoqkh7XpHVFiK0=
  on:
    tags: true
    repo: contains-io/typingplus
